version: 2.1

executors:
  docker-executor:
    docker:
     - image: cimg/base:2022.09
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          
      - run: docker build -t nodeapp:latest .

      - run: docker push $DOCKERHUB_USERNAME/nodeapp:latest
    
workflows:
  version: 2
  build_and_push:
    jobs:
      - build

