version: 2.1

executors:
  docker-executor:
    machine:
      image: ubuntu-2204:2022.04.2

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      
      - run:
          name: Build Docker image
          command: docker build -t your_dockerhub_username/your_image_name:latest .
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push your_dockerhub_username/your_image_name:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

