version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli
      - run:
          name: Build Docker image
          command: docker build -t your_dockerhub_username/your_image_name:latest .
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push your_dockerhub_username/your_image_name:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

